-- Dynamic Form Engine Schema

-- 1. Create category_questions table
CREATE TABLE IF NOT EXISTS public.category_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id UUID REFERENCES public.fault_categories(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    field_type TEXT NOT NULL CHECK (field_type IN ('text', 'number', 'yes_no', 'photo', 'select')),
    options TEXT[], -- Array of strings for 'select' type
    is_required BOOLEAN DEFAULT false,
    stage TEXT DEFAULT 'diagnosis' CHECK (stage IN ('diagnosis', 'closing')),
    order_index INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Add form_data to tickets table if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'tickets'
        AND column_name = 'form_data'
    ) THEN
        ALTER TABLE public.tickets ADD COLUMN form_data JSONB DEFAULT '{}'::jsonb;
    END IF;
END $$;

-- 3. RLS Policies for category_questions

-- Enable RLS
ALTER TABLE public.category_questions ENABLE ROW LEVEL SECURITY;

-- Admins can do everything
CREATE POLICY "Admins can manage category_questions"
    ON public.category_questions
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid()
            AND profiles.role = 'admin'
        )
    );

-- Technicians and Managers can view questions
CREATE POLICY "Staff can view category_questions"
    ON public.category_questions
    FOR SELECT
    USING (auth.role() = 'authenticated');
