-- 1. Fault Taxonomy
CREATE TABLE IF NOT EXISTS public.fault_categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name_ar TEXT NOT NULL,
    icon TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Ticket Questions Shell (Future Use)
CREATE TABLE IF NOT EXISTS public.ticket_questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category_id UUID REFERENCES public.fault_categories(id),
    question_text_ar TEXT NOT NULL,
    input_type TEXT CHECK (input_type IN ('text', 'boolean', 'option')),
    is_required BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Workforce & Attendance Logs
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL CHECK (action_type IN ('check_in', 'check_out')),
    timestamp TIMESTAMPTZ DEFAULT now(),
    location_lat FLOAT,
    location_lng FLOAT,
    device_info TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Enhanced Ticket Tracking
-- Adding location verification columns to the tickets table
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tickets' AND column_name = 'start_work_lat') THEN
        ALTER TABLE public.tickets ADD COLUMN start_work_lat FLOAT;
        ALTER TABLE public.tickets ADD COLUMN start_work_lng FLOAT;
        ALTER TABLE public.tickets ADD COLUMN end_work_lat FLOAT;
        ALTER TABLE public.tickets ADD COLUMN end_work_lng FLOAT;
    END IF;
END $$;

-- RLS Policies for Attendance
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own attendance logs"
    ON public.attendance_logs FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own attendance logs"
    ON public.attendance_logs FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can view all attendance logs"
    ON public.attendance_logs FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    );
